### ISSUE TITLE
Add an option to specify magnitude limits of the stars to plot / consider

### ISSUE THREAD

**Issue by orionlee** [exo-pt/TESS-Centroid_vetting#3]
In many cases, the output plot is rather busy with lots of faint stars.

![image](https://github.com/user-attachments/assets/640cf4a9-1312-45ca-a550-8b7e14df265f)

It'd be helpful to let users to optionally specify a custom magnitude limit. An user then can use it to make the plots less busy, with fewer irrelevant faint stars.

**Comment by exo-pt** [comment]
Added in version 1.3.3 (**maglim** parameter)
The testing of the new param showed some flaws in the printing of the stars that, I hope, are now fixed.
